import { ArrowRight, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const content = {
  privacy: { label: "الخصوصية", title: "خصوصيتك أولاً", text: "نغمة تجمع الحد الأدنى من البيانات اللازمة لتحسين البحث وحماية الخدمة. لا نبيع البيانات الشخصية ولا نستخدم إشعارات المتصفح للإعلانات.", sections: ["نخزن سجلات البحث المجهولة لأغراض الأداء فقط.", "يمكنك طلب حذف أي بيانات مرتبطة بطلبك عبر صفحة التواصل.", "نستعمل روابط مؤقتة للملفات التجريبية وتنتهي صلاحيتها تلقائياً."] },
  terms: { label: "الشروط", title: "تجربة مسؤولة", text: "هذه المنصة مخصصة لاكتشاف الموسيقى والاطلاع على metadata المصرح بها. تجربة التحويل توضيحية ومحدودة بالملفات التجريبية أو المرخصة.", sections: ["لا يتم تجاوز حماية YouTube أو تنزيل محتوى غير مصرح به.", "يجب احترام حقوق الفنانين وأصحاب الحقوق.", "نحتفظ بحق تعطيل أي عنصر عند ورود طلب إزالة صالح."] },
  dmca: { label: "طلبات السحب", title: "سياسة الإزالة", text: "إذا كنت صاحب حق وتعتقد أن عنصراً منشوراً يخالف حقوقك، أرسل تفاصيل واضحة وسنراجع الطلب بسرعة.", sections: ["أرسل اسمك، بريدك، ورابط الصفحة المعنية.", "اشرح طبيعة الحق والسبب القانوني للطلب.", "تواصل معنا عبر support@naghmahub.example وسنؤكد استلام الطلب."] },
  contact: { label: "تواصل", title: "نحن نصغي", text: "للاستفسارات التقنية أو اقتراحات المحتوى أو طلبات السحب، اكتب لنا رسالة واضحة.", sections: ["البريد: support@naghmahub.example", "نرد على الطلبات خلال أيام العمل.", "لا ترسل كلمات مرور أو معلومات مالية عبر النموذج."] },
} as const;

export default function LegalPage({ kind }: { kind: keyof typeof content }) { const item = content[kind]; return <div className="mx-auto max-w-3xl px-5 pb-12 pt-8"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-[#756590]"><ArrowRight size={16} /> العودة للرئيسية</Link><article className="soft-card rounded-[32px] p-7 sm:p-12"><span className="inline-flex items-center gap-2 rounded-full bg-[#effaf5] px-4 py-2 text-xs font-bold text-[#477363]"><ShieldCheck size={14} /> {item.label}</span><h1 className="serif mt-5 text-5xl text-[#514568]">{item.title}</h1><p className="mt-5 text-base leading-8 text-[#81768f]">{item.text}</p><div className="mt-10 space-y-4">{item.sections.map(section => <div key={section} className="flex gap-3 border-b border-[#756590]/10 pb-4 text-sm leading-7 text-[#635978]"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#a98bb6]" />{section}</div>)}</div>{kind === "contact" && <a href="mailto:support@naghmahub.example" className="mt-10 inline-flex items-center gap-2 rounded-xl bg-[#756590] px-5 py-3 text-sm font-bold text-white"><Mail size={16} /> أرسل رسالة</a>}</article></div>; }
