import { ArrowRight, Mail, ShieldCheck } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const content = {
  privacy: { label: "الخصوصية", title: "خصوصيتك أولاً", text: "نغمة تجمع الحد الأدنى من البيانات اللازمة لتحسين البحث وحماية الخدمة. لا نبيع البيانات الشخصية ولا نستخدم إشعارات المتصفح للإعلانات.", sections: ["نخزن سجلات البحث المجهولة لأغراض الأداء فقط.", "يمكنك طلب حذف أي بيانات مرتبطة بطلبك عبر صفحة التواصل.", "نستعمل روابط مؤقتة للملفات التجريبية وتنتهي صلاحيتها تلقائياً."] },
  terms: { label: "الشروط", title: "تجربة مسؤولة", text: "هذه المنصة مخصصة لاكتشاف الموسيقى والاطلاع على metadata المصرح بها. تجربة التحويل توضيحية ومحدودة بالملفات التجريبية أو المرخصة.", sections: ["لا يتم تجاوز حماية YouTube أو تنزيل محتوى غير مصرح به.", "يجب احترام حقوق الفنانين وأصحاب الحقوق.", "نحتفظ بحق تعطيل أي عنصر عند ورود طلب إزالة صالح."] },
  dmca: { label: "طلبات السحب", title: "سياسة الإزالة", text: "إذا كنت صاحب حق وتعتقد أن عنصراً منشوراً يخالف حقوقك، أرسل تفاصيل واضحة وسنراجع الطلب بسرعة.", sections: ["أرسل اسمك، بريدك، ورابط الصفحة المعنية.", "اشرح طبيعة الحق والسبب القانوني للطلب.", "سيظهر الطلب في لوحة الإدارة بحالة مفتوح إلى أن تتم مراجعته."] },
  contact: { label: "تواصل", title: "نحن نصغي", text: "للاستفسارات التقنية أو اقتراحات المحتوى أو طلبات السحب، اكتب لنا رسالة واضحة.", sections: ["البريد: support@naghmahub.example", "نرد على الطلبات خلال أيام العمل.", "لا ترسل كلمات مرور أو معلومات مالية عبر النموذج."] },
} as const;

export default function LegalPage({ kind }: { kind: keyof typeof content }) {
  const item = content[kind];
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [reason, setReason] = useState("");
  const [evidenceUrl, setEvidenceUrl] = useState("");
  const takedown = trpc.takedown.submit.useMutation();
  const submit = (event: FormEvent) => { event.preventDefault(); takedown.mutate({ claimantName: name, claimantEmail: email, reason, evidenceUrl: evidenceUrl || undefined }); };
  return <div className="mx-auto max-w-3xl px-5 pb-12 pt-8"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-[#756590]"><ArrowRight size={16} /> العودة للرئيسية</Link><article className="soft-card rounded-[32px] p-7 sm:p-12"><span className="inline-flex items-center gap-2 rounded-full bg-[#effaf5] px-4 py-2 text-xs font-bold text-[#477363]"><ShieldCheck size={14} /> {item.label}</span><h1 className="serif mt-5 text-5xl text-[#514568]">{item.title}</h1><p className="mt-5 text-base leading-8 text-[#81768f]">{item.text}</p><div className="mt-10 space-y-4">{item.sections.map(section => <div key={section} className="flex gap-3 border-b border-[#756590]/10 pb-4 text-sm leading-7 text-[#635978]"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#a98bb6]" />{section}</div>)}</div>{kind === "dmca" && <form onSubmit={submit} className="mt-10 space-y-3 border-t border-[#756590]/10 pt-8"><h2 className="font-bold text-[#514568]">إرسال طلب سحب</h2><input required value={name} onChange={e => setName(e.target.value)} placeholder="الاسم الكامل" className="w-full rounded-xl border border-[#756590]/15 bg-white/70 px-4 py-3 text-sm text-[#514568]" /><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="w-full rounded-xl border border-[#756590]/15 bg-white/70 px-4 py-3 text-sm text-[#514568]" /><input type="url" value={evidenceUrl} onChange={e => setEvidenceUrl(e.target.value)} placeholder="رابط الصفحة أو الإثبات (اختياري)" className="w-full rounded-xl border border-[#756590]/15 bg-white/70 px-4 py-3 text-sm text-[#514568]" /><textarea required minLength={20} value={reason} onChange={e => setReason(e.target.value)} placeholder="اشرح الحق والسبب القانوني للطلب (20 حرفاً على الأقل)" className="min-h-32 w-full rounded-xl border border-[#756590]/15 bg-white/70 px-4 py-3 text-sm text-[#514568]" />{takedown.isSuccess && <p className="rounded-xl bg-[#effaf5] p-3 text-sm text-[#477363]">تم استلام الطلب وتسجيله للمراجعة.</p>}{takedown.isError && <p className="rounded-xl bg-[#fff3f5] p-3 text-sm text-[#a86f87]">تعذر تسجيل الطلب حالياً، حاول لاحقاً.</p>}<button type="submit" disabled={takedown.isPending} className="rounded-xl bg-[#756590] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{takedown.isPending ? "جارٍ الإرسال…" : "إرسال الطلب"}</button></form>}{kind === "contact" && <a href="mailto:support@naghmahub.example" className="mt-10 inline-flex items-center gap-2 rounded-xl bg-[#756590] px-5 py-3 text-sm font-bold text-white"><Mail size={16} /> أرسل رسالة</a>}</article></div>;
}
