import { CheckCircle2, Download, FileAudio, FileVideo, Loader2, ShieldCheck } from "lucide-react";
import { Link, useSearch } from "wouter";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

export default function MediaPage() {
  const params = new URLSearchParams(useSearch());
  const token = params.get("d") || "";
  const [format, setFormat] = useState<"mp3" | "mp4">("mp3");
  const [job, setJob] = useState<{ status: string; progress: number; downloadUrl: string; notice: string } | null>(null);
  const { data: media, isLoading, error } = trpc.catalog.mediaByToken.useQuery({ token }, { enabled: Boolean(token) });
  const convert = trpc.catalog.startDemoConversion.useMutation({ onSuccess: setJob });
  if (isLoading) return <div className="mx-auto max-w-3xl px-5 py-20"><div className="h-96 animate-pulse rounded-[32px] bg-white/60" /></div>;
  if (error || !media) return <div className="mx-auto max-w-3xl px-5 py-20 text-center"><p className="serif text-4xl text-[#514568]">الرابط غير صالح أو منتهي</p><Link href="/" className="mt-4 inline-block font-bold text-[#756590]">العودة للرئيسية</Link></div>;
  return <div className="mx-auto max-w-3xl px-5 pb-12 pt-12"><div className="soft-card rounded-[32px] p-6 sm:p-10"><div className="flex items-start gap-4"><FileAudio className="mt-1 rounded-xl bg-[#eee8f7] p-3 text-[#756590]" size={52} /><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#9d8aae]">مساحة الوسائط</p><h1 className="serif mt-2 text-4xl text-[#514568]">{media.title}</h1><p className="mt-1 text-sm text-[#81768f]">{media.artist || "فنان تجريبي"} · {media.duration}</p></div></div><div className="mt-8 rounded-2xl bg-[#f6f1fa] p-4 text-sm text-[#756590]"><span className="font-bold">كود الملف:</span> {media.opaqueToken}</div><div className="mt-8 flex gap-2 rounded-2xl bg-[#fbf9fd] p-2">{(["mp3", "mp4"] as const).map(item => <button key={item} onClick={() => setFormat(item)} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold transition ${format === item ? "bg-[#756590] text-white" : "text-[#81768f] hover:bg-white"}`}>{item === "mp3" ? <span className="inline-flex items-center gap-2"><FileAudio size={16} /> صوت MP3</span> : <span className="inline-flex items-center gap-2"><FileVideo size={16} /> فيديو MP4</span>}</button>)}</div><div className="mt-4 flex items-center justify-between rounded-2xl border border-[#756590]/10 bg-white/60 p-4"><div><p className="font-bold text-[#514568]">{format === "mp3" ? "Demo 128 kbps" : "Demo 720p"}</p><p className="text-xs text-[#9d8aae]">ملف توضيحي مصرح · رابط 15 دقيقة</p></div><button disabled={convert.isPending || Boolean(job)} onClick={() => convert.mutate({ token, format, quality: format === "mp3" ? "128kbps" : "720p" })} className="inline-flex items-center gap-2 rounded-xl bg-[#756590] px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{convert.isPending ? <Loader2 className="animate-spin" size={16} /> : job ? <CheckCircle2 size={16} /> : <Download size={16} />}{job ? "جاهز" : "تحويل تجريبي"}</button></div>{job && <div className="mt-5 rounded-2xl border border-[#b9dfd2] bg-[#effaf5] p-4 text-sm text-[#477363]"><p className="flex items-center gap-2 font-bold"><CheckCircle2 size={16} /> اكتمل التحويل التوضيحي</p><p className="mt-1">{job.notice}</p><a href={job.downloadUrl} onClick={e => e.preventDefault()} className="mt-3 inline-flex items-center gap-2 font-bold underline"><Download size={15} /> رابط مؤقت تجريبي</a></div>}<p className="mt-7 flex items-start gap-2 text-xs leading-6 text-[#8c819f]"><ShieldCheck className="mt-1 shrink-0" size={15} /> لا يتم جلب أو تنزيل أي محتوى من YouTube. هذه الواجهة تعرض تجربة ملفات تجريبية مصرح بها فقط.</p></div></div>;
}
