import { ArrowRight, Clock3, Disc3, Download, Play, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useEffect } from "react";
import { trpc } from "@/lib/trpc";
import { MusicCard, SectionHeading } from "@/components/MusicCard";

export default function SongPage() {
  const [, params] = useRoute("/s/:slug");
  const { data: song, isLoading, error } = trpc.catalog.songBySlug.useQuery({ slug: params?.slug ?? "" });
  const { data: related = [] } = trpc.catalog.trending.useQuery({ limit: 3 });
  useEffect(() => { if (song) { document.title = `${song.title} — نغمة`; const description = `اكتشف ${song.title} من ${song.artist || "فنان تجريبي"} على نغمة.`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement("meta"); meta.setAttribute("name", "description"); document.head.appendChild(meta); } meta.setAttribute("content", description); let jsonLd = document.getElementById("song-jsonld"); if (!jsonLd) { jsonLd = document.createElement("script"); jsonLd.id = "song-jsonld"; jsonLd.setAttribute("type", "application/ld+json"); document.head.appendChild(jsonLd); } jsonLd.textContent = JSON.stringify({ "@context": "https://schema.org", "@type": "MusicRecording", name: song.title, byArtist: { "@type": "MusicGroup", name: song.artist || "فنان تجريبي" }, duration: `PT${song.durationSeconds ?? 0}S`, url: window.location.href }); } return () => { document.title = "نغمة | NaghmaHub"; document.getElementById("song-jsonld")?.remove(); }; }, [song]);
  if (isLoading) return <div className="mx-auto max-w-6xl px-5 py-20"><div className="h-80 animate-pulse rounded-[32px] bg-white/60" /></div>;
  if (error || !song) return <div className="mx-auto max-w-6xl px-5 py-20 text-center"><p className="serif text-4xl text-[#514568]">المقطع غير موجود</p><Link href="/" className="mt-4 inline-block font-bold text-[#756590]">العودة للرئيسية</Link></div>;
  return <div className="mx-auto max-w-6xl px-5 pb-12 pt-8"><Link href="/search" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-[#756590]"><ArrowRight size={16} /> العودة للنتائج</Link><section className="corner-frame soft-card grid gap-8 rounded-[32px] p-6 md:grid-cols-[260px_1fr] md:p-10"><img src={song.thumbnailUrl || "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=80"} alt="" className="aspect-square w-full rounded-[26px] object-cover" /><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#9d8aae]">تفاصيل الإصدار</p><h1 className="serif mt-3 text-5xl leading-tight text-[#514568]">{song.title}</h1><p className="mt-3 text-lg text-[#81768f]">{song.artist || "فنان تجريبي"}</p><div className="mt-6 flex flex-wrap gap-4 text-sm text-[#81768f]"><span className="inline-flex items-center gap-2"><Disc3 size={16} /> {song.album || "إصدار تجريبي"}</span><span className="inline-flex items-center gap-2"><Clock3 size={16} /> {song.duration}</span></div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/media?d=${encodeURIComponent(song.opaqueToken)}`} className="inline-flex items-center gap-2 rounded-xl bg-[#756590] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#756590]/20"><Download size={17} /> تجربة التحميل</Link><a href={`https://www.youtube.com/watch?v=${song.providerVideoId}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#756590]/15 bg-white/60 px-5 py-3 text-sm font-bold text-[#756590]"><Play size={16} /> المصدر</a></div><p className="mt-5 inline-flex items-center gap-2 text-xs text-[#8c819f]"><ShieldCheck size={14} /> هذا عنصر تجريبي؛ لا يتم تنزيل محتوى خارجي.</p></div></section><section className="mt-16"><SectionHeading eyebrow="ربما يعجبك" title="استكشف أكثر" /><div className="grid gap-4 sm:grid-cols-3">{related.filter(item => item.slug !== song.slug).map(item => <MusicCard key={item.id} song={item} compact />)}</div></section></div>;
}
