import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import {z} from 'zod';
import crypto from 'node:crypto';
import 'dotenv/config';

const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'100kb'}));
const limiter=rateLimit({windowMs:60_000,max:60,standardHeaders:true});
app.use('/api',limiter);

type Song={id:number;title:string;artist:string;slug:string;provider:string;providerVideoId:string;thumbnailUrl:string|null;durationSeconds:number;rightsStatus:'metadata-only'|'licensed'};
const demo:Song[]=Array.from({length:20},(_,i)=>({id:i+1,title:['ليلة هادئة','على شاطئ الذكرى','صوت المدينة','أغنية الصباح','بين السطور'][i%5]+' '+(i+1),artist:['فرقة نغم','سلمى نور','مدار','رؤى','أفق'][i%5],slug:`demo-song-${i+1}`,provider:'demo',providerVideoId:`demo-${String(i+1).padStart(4,'0')}`,thumbnailUrl:null,durationSeconds:180+i,rightsStatus:'metadata-only'}));
const tokens=new Map<string,{songId:number,expires:number}>();
const tokenSecret=()=>process.env.TOKEN_SECRET||'development-secret-change-me';
const makeToken=(songId:number)=>{const raw=crypto.randomBytes(32).toString('base64url');const exp=Date.now()+10*60_000;const body=`${raw}.${exp}`;const sig=crypto.createHmac('sha256',tokenSecret()).update(body).digest('base64url');tokens.set(raw,{songId,expires:exp});return `${body}.${sig}`};
const normalize=(s:string)=>s.normalize('NFKC').toLocaleLowerCase('ar').replace(/[ًٌٍَُِّْـ]/g,'').replace(/\s+/g,' ').trim();
const searchSchema=z.object({q:z.string().trim().max(100).default(''),page:z.coerce.number().int().min(1).default(1)});
app.get('/api/search',(req,res)=>{const p=searchSchema.safeParse(req.query);if(!p.success)return res.status(400).json({error:'invalid_query'});const q=normalize(p.data.q);const items=demo.filter(s=>normalize(`${s.title} ${s.artist}`).includes(q));res.json({items,total:items.length,page:p.data.page,pageSize:20});});
app.get('/api/trending',(_req,res)=>res.json({items:demo.slice(0,12),total:12}));
app.get('/api/songs/:slug',(req,res)=>{const s=demo.find(x=>x.slug===req.params.slug);if(!s)return res.status(404).json({error:'not_found'});res.json(s);});
app.get('/api/media/resolve',(req,res)=>{const parsed=z.string().min(20).max(220).safeParse(req.query.d);if(!parsed.success)return res.status(400).json({error:'invalid_token'});const parts=parsed.data.split('.');if(parts.length!==3)return res.status(403).json({error:'invalid_token'});const [raw,exp,sig]=parts;const expected=crypto.createHmac('sha256',tokenSecret()).update(`${raw}.${exp}`).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return res.status(403).json({error:'invalid_token'});const record=tokens.get(raw);if(!record||record.expires<Date.now()||Number(exp)!==record.expires)return res.status(410).json({error:'expired'});const song=demo.find(s=>s.id===record.songId);res.json({song,variants:song?.rightsStatus==='licensed'?[{format:'MP3',quality:'128 kbps'},{format:'MP3',quality:'320 kbps'},{format:'MP4',quality:'360p'},{format:'MP4',quality:'720p'}]:[]});});
app.post('/api/conversions',(req,res)=>{const p=z.object({songId:z.number().int(),format:z.enum(['MP3','MP4']),quality:z.string().max(20)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'invalid_request'});const song=demo.find(s=>s.id===p.data.songId);if(!song||song.rightsStatus!=='licensed')return res.status(403).json({error:'media_not_authorized'});res.status(202).json({id:crypto.randomUUID(),status:'queued',progress:0});});
app.get('/api/conversions/:id',(req,res)=>res.json({id:req.params.id,status:'queued',progress:0}));
app.post('/api/contact',(req,res)=>{const p=z.object({email:z.string().email(),message:z.string().min(10).max(2000)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'invalid_contact'});res.status(201).json({ok:true});});
app.get('/api/download/:token',(_req,res)=>res.status(410).json({error:'no_licensed_file',message:'No authorized media file is available for this demo catalog.'}));
app.listen(Number(process.env.PORT||3001),()=>console.log('NaghmaHub API listening on 3001'));
