import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useSearchParams,useParams,Routes,Route,Link} from 'react-router-dom';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {Search, Moon, Sun, Music2, Download, Eye, Clock3, ArrowLeft, ShieldCheck, Sparkles} from 'lucide-react';
import './style.css';

const qc=new QueryClient();
type Song={id:number;title:string;artist:string;slug:string;thumbnailUrl?:string|null;durationSeconds?:number|null;provider?:string;providerVideoId?:string;rightsStatus?:string;availabilityStatus?:string};
const api=async<T>(url:string):Promise<T>=>{const r=await fetch(url);if(!r.ok)throw new Error('api_error');return r.json()};
const fmt=(s?:number|null)=>s==null?'—':`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function useTheme(){const [dark,setDark]=useState(()=>localStorage.getItem('naghma-theme')==='dark');React.useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('naghma-theme',dark?'dark':'light')},[dark]);return [dark,()=>setDark(v=>!v)] as const}
function Layout({children}:{children:React.ReactNode}){const [dark,toggle]=useTheme();return <div className="app" dir="rtl"><header><div className="container nav"><Link to="/" className="brand"><span className="brandmark"><Music2 size={20}/></span><span>NaghmaHub</span></Link><nav><Link to="/trending">الرائج</Link><Link to="/contact">تواصل معنا</Link><Link to="/dmca">حقوق النشر</Link></nav><button className="icon" onClick={toggle} aria-label="تبديل المظهر">{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header>{children}<footer><div className="container footer"><span>© {new Date().getFullYear()} NaghmaHub</span><span>منصة اكتشاف موسيقى ببيانات مرخصة أو مصرح بها.</span></div></footer></div>}
function SearchBox(){const [q,setQ]=useState('');const nav=useNavigate();return <form className="search" onSubmit={e=>{e.preventDefault();if(q.trim())nav('/search?q='+encodeURIComponent(q.trim()))}}><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="إبحث عن أغنية أو ألبوم أو فنان" aria-label="البحث"/><button>بحث</button></form>}
function Ad(){return <div className="ad" aria-label="مساحة إعلانية">إعلان — مساحة مخصصة للإعلانات</div>}
function SongCard({s}:{s:Song}){return <article className="song"><div className="cover">{s.thumbnailUrl?<img src={s.thumbnailUrl} alt="" loading="lazy"/>:<Music2 size={28}/>}</div><div className="songmeta"><Link to={'/s/'+s.slug} className="title">{s.title}</Link><span>{s.artist}</span><small><Clock3 size={13}/>{fmt(s.durationSeconds)}</small></div><div className="actions"><Link className="btn ghost" to={'/s/'+s.slug}><Eye size={16}/>تفاصيل</Link>{s.rightsStatus==='licensed'?<Link className="btn" to={'/media?d='+s.slug}><Download size={16}/>تحميل</Link>:<span className="legal">بيانات فقط</span>}</div></article>}
function Home(){const {data}=useQuery({queryKey:['trending'],queryFn:()=>api<{items:Song[]}>('/api/trending')});return <main className="container"><section className="hero"><div className="heroicon"><Sparkles/></div><h1>اكتشف نغماتك المفضلة</h1><p>ابحث عن الأغاني والفنانين والألبومات في كتالوج سريع ومرتب.</p><SearchBox/><Ad/></section><section><div className="sectionhead"><h2>الأغاني الرائجة</h2><Link to="/trending">عرض الكل</Link></div><div className="list">{(data?.items||[]).slice(0,8).map(s=><SongCard key={s.id} s={s}/>)}</div></section></main>}
function SearchPage(){const [sp]=useSearchParams();const q=sp.get('q')||'';const {data,isLoading,isError}=useQuery({queryKey:['search',q],queryFn:()=>api<{items:Song[];total:number}>('/api/search?q='+encodeURIComponent(q))});return <main className="container page"><div className="back"><Link to="/"><ArrowLeft size={16}/>الرئيسية</Link></div><h1>نتائج البحث</h1><p className="muted">{q?`نتائج البحث عن «${q}»`:'اكتب كلمة للبحث'}</p>{isLoading?<Skeleton/>:isError?<div className="state">تعذر تحميل النتائج. حاول مرة أخرى.</div>:!data?.items.length?<div className="state">لم نجد نتائج مطابقة.</div>:<><div className="list">{data.items.map(s=><SongCard key={s.id} s={s}/>)}</div><Ad/></>}</main>}
function Skeleton(){return <div className="list">{Array.from({length:6}).map((_,i)=><div className="skeleton" key={i}/>)}</div>}
function SongPage(){const {slug}=useParams();const {data,isLoading}=useQuery({queryKey:['song',slug],queryFn:()=>api<Song>('/api/songs/'+slug)});if(isLoading)return <main className="container page"><Skeleton/></main>;if(!data)return <main className="container page"><div className="state">الأغنية غير موجودة.</div></main>;return <main className="container page"><div className="detail"><div className="detailcover">{data.thumbnailUrl?<img src={data.thumbnailUrl} alt=""/>:<Music2 size={54}/>}</div><div><span className="eyebrow">{data.provider||'catalog'}</span><h1>{data.title}</h1><h2>{data.artist}</h2><div className="facts"><span><Clock3 size={15}/>{fmt(data.durationSeconds)}</span><span><ShieldCheck size={15}/>{data.rightsStatus==='licensed'?'مصرح بالمعالجة':'بيانات وصفية'}</span></div><div className="detailactions"><Link className="btn" to={data.rightsStatus==='licensed'?'/media?d='+data.slug:'#'}><Download size={17}/>تحميل</Link><a className="btn ghost" href={data.providerVideoId?'https://www.youtube.com/watch?v='+encodeURIComponent(data.providerVideoId):'#'} target="_blank" rel="noreferrer">مشاهدة</a></div></div></div><Ad/><h2 className="relatedtitle">معلومات الاستخدام</h2><p className="muted">تظهر أزرار المعالجة والتنزيل فقط للمصادر التي يملك الموقع حق استخدامها أو معالجتها. YouTube API هنا مخصص للبيانات الوصفية ولا يوفر روابط MP3.</p></main>}
function Trending(){const {data}=useQuery({queryKey:['trending'],queryFn:()=>api<{items:Song[]}>('/api/trending')});return <main className="container page"><h1>الرائج</h1><p className="muted">أحدث العناصر التي تتمتع بأعلى نشاط في الكتالوج.</p><div className="list">{(data?.items||[]).map(s=><SongCard key={s.id} s={s}/>)}</div></main>}
function Info({title,children}:{title:string;children:React.ReactNode}){return <main className="container page prose"><h1>{title}</h1>{children}</main>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/s/:slug" element={<SongPage/>}/><Route path="/trending" element={<Trending/>}/><Route path="/media" element={<Info title="الوسائط"><p>صفحة الوسائط مخصصة للملفات المرخصة فقط. يتم إصدار روابط التنزيل الموقعة لفترة قصيرة من الخادم.</p></Info>}/><Route path="/videos_dl" element={<Info title="المعالجة"><p>لا تتم معالجة محتوى طرف ثالث دون تصريح. عند توفر مصدر مرخص، يعرض الخادم حالة المهمة ورابطاً مؤقتاً.</p></Info>}/><Route path="/contact" element={<Info title="تواصل معنا"><p>للاستفسارات والدعم وطلبات التعديل أو الحذف، استخدم قناة التواصل المخصصة في إعدادات النشر.</p></Info>}/><Route path="/dmca" element={<Info title="حقوق النشر"><p>نحترم حقوق أصحاب المحتوى. يمكن لصاحب الحق إرسال طلب إزالة موثق، وستتم مراجعة السجل واتخاذ الإجراء المناسب.</p></Info>}/><Route path="/terms" element={<Info title="الشروط والخصوصية"><p>الخدمة مخصصة لاكتشاف المحتوى والبيانات الوصفية المصرح باستخدامها. لا يجوز استخدام المنصة لانتهاك حقوق الغير.</p></Info>}/></Routes>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={qc}><BrowserRouter><Layout><App/></Layout></BrowserRouter></QueryClientProvider>);
